# Generated by Django 3.0.8 on 2020-07-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_tracker', models.CharField(blank=True, max_length=255, null=True)),
                ('date_mood', models.DateField(blank=True, null=True)),
                ('sleep_tracker', models.CharField(blank=True, max_length=255, null=True)),
                ('date_sleep', models.DateField(blank=True, null=True)),
                ('ways_help', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_alerts', models.CharField(blank=True, max_length=255, null=True)),
                ('self_care', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_face', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('resources', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
