# Generated by Django 3.0.8 on 2020-07-30 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suicideprevent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mood',
            old_name='ways_help',
            new_name='affirmations',
        ),
    ]
