# Generated by Django 3.0.8 on 2020-08-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suicideprevent', '0002_auto_20200730_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='my_week',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
