# Generated by Django 3.0.8 on 2020-08-05 13:48

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('suicideprevent', '0003_auto_20200805_1337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='ProfileFace',
        ),
        migrations.AddField(
            model_name='mood',
            name='city',
            field=models.CharField(default='0000000', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='mood',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='0000000', editable=False, max_length=63),
        ),
        migrations.AddField(
            model_name='mood',
            name='profile_face',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
