# Generated by Django 3.0.8 on 2020-08-05 19:22

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('suicideprevent', '0004_auto_20200805_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
