# Generated by Django 3.1 on 2020-08-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suicideprevent', '0005_auto_20200805_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_face', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('mood', models.CharField(blank=True, max_length=255, null=True)),
                ('date_added', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='mood',
            old_name='affirmations',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mood',
            old_name='emergency_contact',
            new_name='smile_emoji',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='city',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='date_mood',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='date_sleep',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='location',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='mood_tracker',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='notification_alerts',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='profile_face',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='self_care',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='sleep_tracker',
        ),
    ]
