# Generated by Django 3.1 on 2020-08-11 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suicideprevent', '0006_auto_20200810_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smile_emoji', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='moodtracker',
            name='mood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='suicideprevent.mood'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SleepTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_face', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('date_added', models.DateField(auto_now_add=True, null=True)),
                ('sleep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suicideprevent.sleep')),
            ],
        ),
    ]
